name: nfl_test
channels:
    - conda-forge
    - default
dependencies:
  - pip=21.2.4
  - python=3.9
  - notebook
  - pandas
  - numpyte
  - requests
  - pillow
  - seaborn
  - pip:
    - SQLAlchemy
    - python-dotenv
    - espn_api
